prac-enabled: '<#456973>[<#1cc6ff><bold><italic>7<white>o<reset><#456973>] <#bcd0d6>Enabled practice mode.'
prac-disabled: '<#456973>[<#1cc6ff><bold><italic>7<white>o<reset><#456973>] <#bcd0d6>Disabled practice mode.'
prac-already-enabled: '<#545454>[<#cc1414><bold><italic>7<white>o<reset><#545454>] <#c79d9d>You are already in practice mode.'
must-be-on-ground: '<#545454>[<#cc1414><bold><italic>7<white>o<reset><#545454>] <#c79d9d>You must be on ground.'
not-in-prac: '<#545454>[<#cc1414><bold><italic>7<white>o<reset><#545454>] <#c79d9d>You are not in practice mode.'
temp-prac-location-set: '<#456973>[<#1cc6ff><bold><italic>7<white>o<reset><#456973>] <#bcd0d6>Practice checkpoint set.'