name: QuantumParkour
version: 1.0.0
main: com.quantumparkour.QuantumParkour
api-version: '1.21'
authors: [ Diabet, Nova ]
description: Custom coded parkour plugin batch for QuantumParkour. 

softdepend: [PlaceholderAPI, AnimatedScoreboard]
